# Generated by Django 4.1.7 on 2023-04-30 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 1, 53, 2, 853133)),
        ),
    ]
