# Generated by Django 4.1.7 on 2023-05-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
