# Generated by Django 4.1.7 on 2023-04-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_article_content_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='totalViews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.article'),
        ),
    ]
